name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/php

      - uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          vuln-type: library,os
          severity: HIGH,CRITICAL
          exit-code: 0   

      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --exit-code 0
